apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-sa
  namespace: local-path-storage

# ---------------------------------------------------------
# ЛОКАЛЬНЫЕ ПРАВА (Для создания helper-pods, которые делают mkdir/rm)
# ---------------------------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: local-path-provisioner-local-role
  namespace: local-path-storage
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: local-path-provisioner-local-bind
  namespace: local-path-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: local-path-provisioner-local-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-sa
    namespace: local-path-storage

# ---------------------------------------------------------
# ГЛОБАЛЬНЫЕ ПРАВА (Для слежения за требованиями дисков по всему кластеру)
# ---------------------------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-global-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps", "pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-global-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-global-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-sa
    namespace: local-path-storage
